UPDATE PRODUCTOS
SET NOMBRE_ARTICULO = 'Silla Ergonomica', CANTIDAD = 5
WHERE ID = 4;

UPDATE CATEGORIA
SET NOMBRE = 'MUEBLES', DESCRIPCION = 'MUEBLES DE OFICINA'
WHERE ID = 2;

DELETE FROM USUARIOS
WHERE ID > 1;

UPDATE USUARIOS
SET NOMBRE = 'Usuario Prueba', 
CORREO = 'test@gmail.com'
where ID = 1;